version: '3'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    image: react
    container_name: react
    restart: unless-stopped
    networks:
      - app-network-2

  nginx2:
    image: nginx:mainline-alpine
    container_name: nginx2
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - react
    networks:
      - app-network-2

networks:
  app-network-2:
    driver: bridge  